### ISSUE TITLE
novendor: add option to ignore packages

### ISSUE THREAD

**Issue by bmoylan** [palantir/checks#39]
If I configure novendor to ignore a package, it should automatically ignore dependencies of that package.

The current state of the world is a long list of exclusions that is difficult to keep up to date.

**Comment by nmiyake** [comment]
`novendor` currently doesn't provide a mechanism for ignoring packages -- what you're referring to is done at the `okgo` level (that tool can be configured to ignore specific output lines of a check, and that's what we're configuring in `check.yml`).

Updating ticket to specify that feature request is to be able to tell `novendor` itself that a specific package should be considered manually whitelisted. As you note in the original request, if we do so, we should consider that package an import root and consider any other transitive dependencies used by that package as imported as well.

**Comment by bmoylan** [comment]
sounds good, thanks!
